// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydfgxneyjdtbcwzfrgwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkZmd4bmV5amR0YmN3emZyZ3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzQ5MDcsImV4cCI6MjA2ODYxMDkwN30.EnG-FbV42TO9Y06oalRIOXmsLQZdtHHymgaoJrRIBbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});